### ISSUE TITLE
User Story : Login

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#10]
EPIC: User Authentication and Authorization #1 

As a Site User I am able to Log in to see registerd user sections.

T- shirt : S

**Acceptance Criteria:**
- Be able to login with Username and Password.
- Give an error message if login is unsuccessful.

**Tasks**
- [x] Create a login link for users.
- [x] Create a login form for users to log in with.
- [x] Test that the link and form are working correctly.
