### ISSUE TITLE
User Story : Create Home app

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#14]
EPIC: App Creation #15 

As a Developer I can Create my first django app so that I can use this app for my home page

T- shirt : L

**Acceptance Criteria:**
- Correctly create a new app
- Make sure the app is working correctly

**Tasks:**
- [x] Create app with python3 manage.py startapp home
- [x] Add app to installed apps on settings.py 
- [x] Connect Views url from home app to pp4_project urls
