### ISSUE TITLE
User Story : Create Trading Blog app

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#16]
EPIC: Personal Trading Blog #3 

As a Developer I can create a rescource app so that I can use the app for an extra page on my website to display my trading blog/Journal data from my journal database.

T- shirt : M

**Acceptance Criteria:**
- App is created correctly
- Apps settings are correct

**Tasks:**
- [x] Create app with python3 manage.py startapp resources
- [x] Put 'trading_blog' into installed apps in settings.py
- [x] Add to urlpatterns in urls.py (pp4_project)
