### ISSUE TITLE
User Story : Deploy to & set up Heroku

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#17]
EPIC: Getting startd/Organization #2 

As a Developer I can setup heroku so that I can deploy my project on Heroku

T- shirt : M

**Acceptance Criteria:**
- Set up Heroku correctly
- Deploy to Heroku
- Install a production-ready webserver for Heroku. (guincorn)

**Tasks:**
- [x] Create new Heroku app
- [x] Link to GitHub
- [x] Click on the Settings tab and reveal the config vars. Add a key of DISABLE_COLLECTSTATIC and a value of 1 and click Add.
- [x] Install gunicorn
- [x] Setup Procfile
