### ISSUE TITLE
User Story : Connect PostgreSQL database to code

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#20]
EPIC: Database Models #5 

As a Developer, I can connect my database to my code so that I can store my data to my database.

T- shirt : M

**Acceptance Criteria:**
- Have an env.py file that has set the Value of database url to my new database URL
- Have all installed packages needed to connect code to new Database
- Commented out local database in settings.py
- connected to the environment variable DATABASE_URL 

**Tasks:**
- [x] Create env.py file
- [x] add to gitignore file
- [x] import Python's operating system module and use it to set the value of the DATABASE_URL constant to the URL you copied from ElephantSQL.
- [x] Pip install packages needed to connect to database
- [x] import important settings in settings.py file
- [x] comment out local database
- [x] in the settings.py file, connect to the environment variable DATABASE_URL you previously added to the env.py file
- [x] Migrate
