### ISSUE TITLE
User Story : Create Journal model

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#23]
EPIC: Database Models #5 

As a developer I can create a Journal model so that I can log my Journal data into my database

T- shirt : M

**Acceptance Criteria:**
- Create a model with correct fieldtypes
- As a superuser I can see my created model in my database
- I can enter details into all FieldTypes correctly

**Tasks:**
- [x] from django.contrib.auth.models Import User
- [x] Create Journal model
- [x] Use fieldtypes that I need for my Journal
- [x] Migrate model
- [x] Register model in admin.py
