### ISSUE TITLE
User Story : Create comment model

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#24]
EPIC: Database Model #5 

As a Developer I can create a comment datbase model so that Users can comment on Journal blog posts

T- shirt : XL

**Acceptance Criteria:**
- Model that allows users to comment on posts
- Shows what user commented on the post and at what time
- Comments have to be approved by admin

**Tasks:**
- [x] Create Comment model
- [x] Apply correct filedtypes inlcuding apporved as a BooleanField, so comments can be approved by admin
- [x] Register comment model to admin.py
