### ISSUE TITLE
User Story : Create Views for trading_blog app

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#25]
EPIC: Personal Trading blog #3

As a developer I can code my views.py file so that I can import my models to my views and then see my database via a generic listview on live website.

T- shirt : L

**Acceptance Criteria:**
- Can see posts on live website
- Shows the list from newest to oldest post
- Template connected correctly

**Tasks**:
- [x] Import models
- [x] import generic for listview
- [x] link views to url patterns
- [x] create a class that shows list of posts from newsest to oldest
