### ISSUE TITLE
Uster Story : Admin Panel Power Up

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#26]
EPIC: Style and design of UI #6

As a developer I can download summernote so that superusers have a better layout and format on the admin page.

T- shirt : S

**Acceptance Criteria**:
- Enable better use of admin panel for the superuser
- Include a rich text editor for creating blog posts
- make it an easier proccess of adding and editing blog posts

**Tasks**:
- [x] Install summernote 
- [x] add to requirments.txt
- [x] add to installed apps and url patterns
- [x] import into trading_blog app in admin.py and add a class
- [x] migrate
