### ISSUE TITLE
User Story : Design home page with Bootstrap

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#27]
EPIC: Style & Design of UI #6

As a **developer** I can **design the home page nicely** so that **the users can enjoy a nice UI and understand what the website is all about**

T- shirt : M

**Acceptance Criteria** 
- Users enjoy the look of the Home page
- Users undertand the themes of the home page
- Users understand what the website is all about from the design on the homepage
- Users get a Money heist vibe from the design of the homepage

**Tasks**
- [x] Use Bootstrap for the design of the homepage 
- [x] Use free to use Money heist pictures for hero image and cards images
- [x] Explain to users what the website is about from the design of the home page
- [x] Include three sections. One for the hero image, one for a 'what to expect' section, and the last section will be a 'F.A.Q' section
- [x] Include an accordian. FAQ section.
