### ISSUE TITLE
User Story : Design Journal page with Bootstrap

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#28]
EPIC: Style & Design of UI #6 

As a **developer** I can **style the Journal page** so that **the users will have a nice Journal page to look at**

T- shirt : M

**Acceptance Criteria**
- Style Journal page using Bootstrap
- Users like the look of the Journal page
- Journal page sticks with money heist theme
- Users can see journal entires and click on them to bring them to another page
- Style Journal entries nice and make sure they are clear to read and view

**Tasks**
- [x] Use Bootstrap to layout page
- [x] Use hero image for background
- [x] Connect Journal model to trading_blog views 
- [x] Use cards to display Journal entries to users
- [x] Link cards to post_detail.html
