### ISSUE TITLE
User Story : Open a Journal post

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#29]
EPIC: Personal Trading Blog #3 

As a **user** I can **click on a Journal post** so that **it opens the post and shows me the posts content**

T- shirt : L

**Acceptance Criteria**
- User can click on a post and it opens up the posts content
- post takes user to another page full on the posts content
- content is shown and styled correctly 

**Tasks**
- [x] Add a new path for post detail/Journal detail
- [x] Create new post detail view 
- [x] Create post_detail html file and add necessary code
