### ISSUE TITLE
User Story : Store and use Images via Cloudinary for Superuser for Journal posts

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#30]
EPIC: Getting started/Organization #2 

As a **developer** I can **set up cloudinary** so that **superusers can upload images and store them via cloudinary**

T- shirt : L

**Acceptance Criteria**
- Superusers can upload images to blog posts
- Images are stored on cloudinary

**Tasks**
- [x] Sign up to cloudinary
- [x] Install cloudinary python packages to connect to Cloudinary API
- [x] Add to requirements.txt
- [x] Add to installed apps 
- [x] set enviorn varaible in env.py for cloudinary API url
- [x] import cloudinary field in models.py
- [x] add coudinaryfield to model
- [x] make migrations and migrate
