### ISSUE TITLE
User Story : User can see if they are logged in or not

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#34]
EPIC: #1 User Authentication & Authorization

As a **user** I can **see if I am logged in** so that **I know if I need to log in or not**

T- shirt : M

**Acceptance Criteria**
- Show users if they are logged in or not
- Tell users who is logged in
- Tell users if they are not logged in

**Tasks**
- [x] Use If statements to see If users are logged in or not
- [x] Show users if they are logged in by displaying a message to them on the home and journal pages
- [x] If not logged in tell users they are not logged in with an else statement
