### ISSUE TITLE
User Story : Custom style using css

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#37]
EPIC: Style & Design of UI #6

As a **developer** I can **use css** so that **I can use custom styles for my project**

T- shirt : M

**Acceptance Criteria**
- Custom style parts of project using css
- Use media Queires for better responsiveness

**Tasks**
- [x] Create static folder for static files
- [x] Create CSS folder
- [x] Create style.css file
- [x] Customize styles using css and media Queries
