### ISSUE TITLE
User Story : Users can Delete Comments

### ISSUE THREAD

**Issue by BreakellrZ** [BreakellrZ/trader_base#39]
EPIC: User Interaction on features #7

As a **user** I can **have crud capabilities** so that **the user can delete their comments**

T- shirt : L

**Acceptance Criteria**
- Users can Delete comments

**Tasks**
- [x] Allow users to Delete comments
- [x] Code a modal popup so users can confirm or not confirm a deletion of a comment
- [x] Show Users that their comment has been deleted by text.
